# Generated by Django 5.2.16 on 2026-07-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_request_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('merchant_request_id', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=15)),
                ('amount', models.PositiveIntegerField()),
                ('account_reference', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timeout', 'Timed out')], db_index=True, default='pending', max_length=12)),
                ('result_code', models.IntegerField(blank=True, null=True)),
                ('result_desc', models.CharField(blank=True, max_length=255)),
                ('mpesa_receipt', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('transaction_date', models.CharField(blank=True, max_length=20)),
                ('raw_callback', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
